AllCops:
  Exclude:
    - "lib/any_sms-backend-smsru.rb"

Metrics/BlockLength:
  Exclude:
      - "spec/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Metrics/LineLength:
  Max: 90

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
